language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - wget https://phar.phpunit.de/phpunit-6.5.9.phar

script:
  - php phpunit-6.5.9.phar

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
